name: GitHub Push Webhook

on:
  push:
    branches:
      - main # main 브랜치에 push 시 동작

job:
  send-webhook:
    runs-on: ubuntu-latest


  steps:
     - name: Checkout repository
       uses: actions/checkout@v4

    - name: Send webhook to AWS Lambda
      run: |
        echo "Sending webhook to Lambda..."
        curl -X POST \
          -H "Content-Type: application/json" \
          -d "{\"repository\":\"${{ github.repository }}\", \"ref\":\"${{  github.ref }}\", \"pusher\":
  \"${{github.actor }}\"}"\
          ${{secrets.LAMBDA_URL }}


